### PR TITLE
[CI] - Fixed Celebration Image Bug

### PR DESCRIPTION
**Pull request by adithyaakrishna**
Signed-off-by: Adithya Krishna <aadithya794@gmail.com>

**Description**

This PR fixes the issue of celebration.png not being visible when a new person opens his first PR

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Argh.

**Comment by leecalcote** [comment]
I admit to looking at the change only after merging. 😬 

You'll want to use the raw reference to the image - https://raw.githubusercontent.com/layer5io/preview-layer5/master/.github/welcome/Layer5-celebration.png

**Comment by adithyaakrishna** [comment]
I'll Then create a PR from my another account to check this 👀 
Will use GitHub UI only, so DCO might fail 😶

**Comment by leecalcote** [comment]
Good of you to highlight the possible lack of sign-off. No issue about DCO on items like this. 👍

**Pull request merged**
