### PR TITLE
[CI] Slack.yml updated

### PR DESCRIPTION
**Pull request by aminoxix**
_Signed-off-by_: amino19 anshumaankrprasad76@gmail.com

**Description**
[CI] Workflow existed to `layer5io/meshery` got updated to `layer5io/preview-layer5`

This PR fixes #NA

**Notes for Reviewers**
Needs review to step ahead! :robot: 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by adithyaakrishna — APPROVED** [review]
LGTM 🎉

**Review by leecalcote — CHANGES_REQUESTED** [review]
This repo remains under the `layer5io` org. No need for a change there.

We do need to change from <new-repo> to Layer5 Preview, though.

**Comment by adithyaakrishna** [comment]
My bad I missed this, I accept the responsibility for this.
@amino19 Could you check this?

**Comment by aminoxix** [comment]
@adithyaakrishna : No Sir, not your bad, actually I do that fault! 
Will fix it soon :slightly_smiling_face:

**Comment by leecalcote** [comment]
How dare either of you take responsibility for this when clearly I'm the one to blame! Step aside and let me take the glorious fault here, you greedy martyrs. Don't be stingy with the blame. There's enough to go round. Remember: sharing is caring.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
