### PR TITLE
Image changed in readme file

### LINKED ISSUE #7: [Docs] Replace image in README file
**Current  #State:**
See the white background between the man and woman in the image below that needs to be updated to a better version in the README file.

meshery image issue

**Desired State:**
This is the desired image.
meshery image

Replace with the image below.

layer5-community-sign

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by namitaarya**
Signed off by: Namita Arya <namitaarya2904@gmail.com>

Changed the image in readme file

This PR fixes #7 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
@namitaarya you'd have to make changes in the readme file as well and add that to your commit.

**Comment by namitaarya** [comment]
@warunicorn19 the path to the image (replaced in the folder) used in the readme file is correct from what I see. Could u let me know what do I need to change in the readme file?

**Comment by leecalcote** [comment]
Yay, @namitaarya! 🎈

**Comment by namitaarya** [comment]
Yay @leecalcote Here's some cake for you 🍰

**Pull request merged**
